### ISSUE TITLE
Ubuntu 22.04 LTS support

### ISSUE THREAD

**Issue by dimitrijp** [RADIUSdesk/rdcore#4]
Hello..this is more a query..I playing with installation on upcoming Ubuntu 22.04 LTS without success. After installation I get to login page, but login doesn't work (failure undefined). In nginx error.log there are lots of php errors while trying to login.

Is this php8 issue that ubuntu 22.04 uses by default?

Thanks.

nginx error log;

2022/04/16 17:53:41 [error] 22081#22081: *34 FastCGI sent in stderr: "PHP message: PHP Deprecated:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/rdcore/cake3/rd_cake/vendor/cakephp/cakephp/src/Utility/Text.php on line 232" while reading upstream, client: 192.168.1.62, server: _, request: "POST /cake3/rd_cake/dashboard/authenticate.json HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "192.168.1.5", referrer: "http://192.168.1.5/rd/build/production/Rd/"
2022/04/16 17:53:41 [error] 22081#22081: *34 FastCGI sent in stderr: "PHP mess" while reading upstream, client: 192.168.1.62, server: _, request: "POST /cake3/rd_cake/dashboard/authenticate.json HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "192.168.1.5", referrer: "http://192.168.1.5/rd/build/production/Rd/"
2022/04/16 17:53:41 [error] 22081#22081: *34 FastCGI sent in stderr: "age: PHP Deprecated:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/rdcore/cake3/rd_cake/vendor/cakephp/cakephp/src/Utility/Text.php on line 232PHP message: PHP Deprecated:  str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated in /var/www/rdcore/cake3/rd_cake/vendor/cakephp/cakephp/src/Utility/Text.php on line 232PHP message: PHP Deprecated:  Return type of Cake\Http\Cookie\CookieCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/rdcore/cake3/rd_cake/vendor/cakephp/cakephp/src/Http/Cookie/CookieCollection.php on line 198PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/rdcore/cake3/rd_cake/vendor/cakephp/acl/src/Model/Table/PermissionsTable.php on line 185" while reading upstream, client: 192.168.1.62, server: _, request: "POST /cake3/rd_cake/dashboard/authenticate.json HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "192.168.1.5", referrer: "http://192.168.1.5/rd/build/production/Rd/"

**Comment by dirkvanderwalt** [comment]
Hello,

I will hopefully start testing on 22.04 in the next moths and let you know.
We'll definitely will have to update the install instructions as it seems there are now two versions of PHP to choose from. First prize will naturally be to go with version 8 

Will update you as we progress
