### ISSUE TITLE
under Access provider in login page, "click to connect"  problem

### ISSUE THREAD

**Issue by tattoumz** [RADIUSdesk/rdcore#9]
hi, under any access provider account when i activate click to connect, configure it and save, when i leave tab and open it again, click to connect is no more activated and fields are empty.
work correctly only under root account.
please solve it

**Comment by dirkvanderwalt** [comment]
Hi thanks for the report.

This should fix things for now:

https://github.com/RADIUSdesk/rdcore/commit/fbc51e8b107a943811cc5883f8d216bb6eeb8994

Let us know if it solves your issue :-)
